SET DEFINE OFF

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GH', '가나');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GA', '가봉');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GY', '가이아나');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GM', '감비아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GG', '건지');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('XD', '경제협력개발기구');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GP', '과들루프');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GT', '과테말라');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GU', '괌');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('VA', '교황청');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('UN', '국제연합');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GD', '그레나다');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GR', '그리스');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GL', '그린란드');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GN', '기니');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GW', '기니비사우');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('NA', '나미비아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('NR', '나우루');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('NG', '나이지리아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SS', '남수단');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('ZA', '남아프리카공화국');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('NL', '네덜란드');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('AN', '네덜란드령 안틸레스');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('NP', '네팔연방');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('NO', '노르웨이');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('NC', '뉴 칼레도니아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('NZ', '뉴질랜드');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('NU', '니우에');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('NE', '니제르');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('NI', '니카라과');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('TW', '대만');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('KR', '대한민국');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('DK', '덴마크');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('DO', '도미니카공화국');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('DM', '도미니카연방');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('DE', '독일');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('TL', '동티모르');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('LA', '라오스');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('LR', '라이베리아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('LV', '라트비아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('RU', '러시아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('LB', '레바논');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('LS', '레소토');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('RE', '레위니옹');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('RO', '루마니아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('LU', '룩셈부르크');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('RW', '르완다');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('LY', '리비아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('LT', '리투아니아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('LI', '리히텐슈타인');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MG', '마다가스카르');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MQ', '마르티니크');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MH', '마셜제도');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('YT', '마요트');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('FM', '마이크로네시아연방');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MO', '마카오');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MW', '말라위');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MY', '말레이시아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('ML', '말리');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('IM', '맨 섬');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MX', '멕시코');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MC', '모나코');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MA', '모로코');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MU', '모리셔스');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MR', '모리타니아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MZ', '모잠비크');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('ME', '몬테네그로');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MS', '몬트세랫');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MD', '몰도바');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MV', '몰디브');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MT', '몰타');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MN', '몽골');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MM', '미얀마');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('US', '미합중국');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('VU', '바누아투');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BH', '바레인');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BB', '바베이도스');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BS', '바하마');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BD', '방글라데시');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BM', '버뮤다');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BJ', '베냉');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('VE', '베네수엘라볼리바르');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('VN', '베트남');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BE', '벨기에');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BY', '벨라루스');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BZ', '벨리즈');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BA', '보스니아헤르체고비나');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BW', '보츠와나');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BO', '볼리비아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BI', '부룬디');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BF', '부르키나파소');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BT', '부탄');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MP', '북마리아나 군도');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('MK', '북마케도니아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BG', '불가리아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BR', '브라질');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('BN', '브루나이');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('WS', '사모아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SA', '사우디아라비아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CY', '사이프러스');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('EH', '사하라 아랍민주공화국(서부사하라)');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SM', '산마리노');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('ST', '상투메프린시페');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('PM', '생피에르·미클롱');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SN', '세네갈');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('RS', '세르비아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SC', '세이셸');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SH', '세인트 헬레나 섬');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('LC', '세인트루시아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('VC', '세인트빈센트그레나딘');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('KN', '세인트키츠네비스');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SO', '소말리아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SB', '솔로몬제도');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SD', '수단');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SR', '수리남');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('LK', '스리랑카');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SE', '스웨덴');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CH', '스위스');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('ES', '스페인');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SK', '슬로바키아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SI', '슬로베니아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SY', '시리아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SL', '시에라리온');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SG', '싱가포르');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('AE', '아랍에미리트');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('AW', '아루바');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('AM', '아르메니아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('AR', '아르헨티나');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('XA', '아세안');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('IS', '아이슬란드');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('HT', '아이티');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('IE', '아일랜드');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('AZ', '아제르바이잔');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('AF', '아프가니스탄');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('AD', '안도라');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('AL', '알바니아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('DZ', '알제리');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('AO', '앙골라');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('AG', '앤티가바부다');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('AI', '앵귈라');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('ER', '에리트레아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SZ', '에스와티니');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('EE', '에스토니아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('EC', '에콰도르');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('ET', '에티오피아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('SV', '엘살바도르');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GB', '영국');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('AQ', '영국령 남극지역');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('VG', '영국령 버진 아일랜드');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('IO', '영국령 인도양 제도');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('YE', '예멘');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('OM', '오만');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('AT', '오스트리아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('HN', '온두라스');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('WF', '왈리스·퓌튀나');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('JO', '요르단');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('UG', '우간다');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('UY', '우루과이');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('UZ', '우즈베키스탄');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('UA', '우크라이나');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('XB', '유네스코');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('EU', '유럽연합');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('IQ', '이라크');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('IR', '이란');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('IL', '이스라엘');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('XC', '이슬람 국가');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('EG', '이집트');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('IT', '이탈리아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('IN', '인도');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('ID', '인도네시아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('JP', '일본');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('JM', '자메이카');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('ZM', '잠비아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('JE', '저지');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GQ', '적도기니');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('99', '전체 국가');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GE', '조지아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CN', '중국');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CF', '중앙아프리카');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('DJ', '지부티');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GI', '지브롤터');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('ZW', '짐바브웨');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('TD', '차드');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CZ', '체코');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CL', '칠레');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CM', '카메룬');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CV', '카보베르데');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('KZ', '카자흐스탄');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('QA', '카타르');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('KH', '캄보디아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CA', '캐나다');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('KE', '케냐');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('KY', '케이맨제도');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('KM', '코모로');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('XK', '코소보');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CR', '코스타리카');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CI', '코트디부아르');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CO', '콜롬비아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CG', '콩고');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CD', '콩고민주공화국');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CU', '쿠바');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('KW', '쿠웨이트');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('CK', '쿡제도');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('HR', '크로아티아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('KG', '키르기스스탄');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('KI', '키리바시');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('TJ', '타지키스탄');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('TZ', '탄자니아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('TH', '태국');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('TC', '터크스·케이커스 제도');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('TG', '토고');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('TO', '통가');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('TM', '투르크메니스탄');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('TV', '투발루');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('TN', '튀니지');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('TR', '튀르키예공화국');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('TT', '트리니다드토바고');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('PA', '파나마');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('PY', '파라과이');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('PK', '파키스탄');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('PG', '파푸아뉴기니');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('PW', '팔라우');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('PS', '팔레스타인');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('PE', '페루');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('PT', '포르투갈');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('PL', '폴란드');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('PR', '푸에르토리코');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('FR', '프랑스');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('GF', '프랑스령 기아나');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('PF', '프랑스령 폴리네시아');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('FJ', '피지');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('FI', '핀란드');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('PH', '필리핀');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('PN', '핏케언 섬');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('HU', '헝가리');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('AU', '호주');

INSERT INTO COUNTRY (COUNTRY_CODE, NAME) 
VALUES ('HK', '홍콩');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (1, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (2, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (3, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (4, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (5, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (6, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (7, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (8, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (9, 'RU');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (9, 'HU');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (10, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (11, 'SE');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (11, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (12, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (13, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (14, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (15, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (16, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (17, 'TW');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (18, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (19, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (20, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (20, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (21, 'HU');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (21, 'DE');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (21, 'IT');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (21, 'FR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (22, 'FR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (23, 'CN');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (24, 'BE');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (24, 'NL');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (24, 'FR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (25, 'BE');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (25, 'FR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (26, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (27, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (28, 'FR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (29, 'FR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (30, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (31, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (32, 'CA');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (33, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (34, 'HK');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (34, 'CN');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (35, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (36, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (37, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (38, 'IE');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (38, 'GB');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (38, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (39, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (40, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (41, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (42, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (43, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (44, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (45, 'ES');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (46, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (47, 'FR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (47, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (47, 'GB');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (48, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (49, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (50, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (51, 'CN');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (51, 'HK');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (52, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (53, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (54, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (55, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (56, 'CN');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (57, 'CN');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (58, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (59, 'IN');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (59, 'FR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (59, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (60, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (61, 'HK');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (62, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (63, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (64, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (65, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (66, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (67, 'CN');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (68, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (69, 'IT');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (70, 'IE');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (71, 'BE');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (71, 'CH');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (72, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (73, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (74, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (75, 'IT');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (75, 'BR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (76, 'AU');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (77, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (77, 'HU');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (77, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (78, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (79, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (80, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (81, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (82, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (83, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (84, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (85, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (86, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (87, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (88, 'MN');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (89, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (89, 'FR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (90, 'CA');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (91, 'IT');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (91, 'FR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (91, 'DE');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (92, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (93, 'AU');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (93, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (95, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (96, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (97, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (98, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (99, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (100, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (101, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (102, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (103, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (104, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (105, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (106, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (107, 'CN');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (108, 'FR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (109, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (110, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (111, 'FR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (111, 'ES');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (112, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (113, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (114, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (115, 'RU');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (115, 'HU');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (116, 'NO');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (117, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (118, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (119, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (120, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (120, 'GB');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (121, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (122, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (123, 'CA');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (124, 'FR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (125, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (126, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (127, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (128, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (129, 'IT');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (130, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (131, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (132, 'IT');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (133, 'JP');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (134, 'CA');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (134, 'US');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (135, 'KR');

INSERT INTO MOVIE_COUNTRY (MOVIE_NUM, COUNTRY_CODE) 
VALUES (136, 'KR');

COMMIT